server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver # 设置驱动
    url: jdbc:mysql://115.159.219.176:3306/blog?characterEncoding=UTF-8 #设置数据库，不设置UTF-8会导致中文注释出现乱码
    username: root
    password: abc123
  jpa: # 添加jpa支持
    hibernate:
      ddl-auto: update #update方式避免清空数据
    show-sql: true #打印sql语句
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  #设置创建表时设置的引擎,InnoDB支持事务，MyISAM不支持事务
# security:
#  user:
#    name: admin
#     password: admin # 修改 Spring Security 默认的用户名和密码

